ci(terraform): use new action to check terraform workspace state

diff --git a/.github/workflows/job-terraform-apply.yml b/.github/workflows/job-terraform-apply.yml
--- a/.github/workflows/job-terraform-apply.yml
+++ b/.github/workflows/job-terraform-apply.yml
@@ -25,17 +25,21 @@ jobs:
       # install plugins
       - run: terraform init
 
-      - name: check state
+      - id: terraform-cloud
+        uses: ahmadnassri/action-terraform-cloud-api@v1.0.2
+        with:
+          token: ${{ secrets.TF_TOKEN }}
+          organization: foobar
+          workspace: my-project
+
+      - if: ${{ steps.terraform-cloud.outputs.workspace_locked == 'true' }}
         run: |
-          PROJECT=$(jq -r .backend.config.workspaces.name < .terraform/terraform.tfstate)
-          LOCKED=$(curl -s https://app.terraform.io/api/v2/organizations/${{ github.repository_owner }}/workspaces/$PROJECT -H "Authorization: Bearer ${{ secrets.TF_TOKEN }}" | jq -r '.data.attributes.locked')
-          if [[ $LOCKED == "true" ]]; then
-            echo "::error::state is locked"
-            exit 1
-          fi
+          echo "::error::workspace is locked"
+          exit 1
 
       # execute plan
       - run: terraform apply -auto-approve
+        if: ${{ steps.terraform-cloud.outputs.workspace_locked == 'false' }}
         env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
           CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
