ci(terraform): fix unlock command

diff --git a/.github/workflows/job-terraform-apply.yml b/.github/workflows/job-terraform-apply.yml
--- a/.github/workflows/job-terraform-apply.yml
+++ b/.github/workflows/job-terraform-apply.yml
@@ -9,14 +9,6 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: check state
-        run: |
-          LOCKED=$(curl -s https://app.terraform.io/api/v2/organizations/${{ github.repository_owner }}/workspaces/github -H "Authorization: Bearer ${{ secrets.TF_TOKEN }}" | jq -r '.data.attributes.locked')
-          if [[ $LOCKED == "true" ]]; then
-            echo "::error::state is locked"
-            exit 1
-          fi
-
       - uses: actions/checkout@v3.6.0
 
       - uses: hashicorp/setup-terraform@v2.0.3
@@ -32,6 +24,15 @@ jobs:
 
       # install plugins
       - run: terraform init
+
+      - name: check state
+        run: |
+          PROJECT=$(jq -r .backend.config.workspaces.name < .terraform/terraform.tfstate)
+          LOCKED=$(curl -s https://app.terraform.io/api/v2/organizations/${{ github.repository_owner }}/workspaces/$PROJECT -H "Authorization: Bearer ${{ secrets.TF_TOKEN }}" | jq -r '.data.attributes.locked')
+          if [[ $LOCKED == "true" ]]; then
+            echo "::error::state is locked"
+            exit 1
+          fi
 
       # execute plan
       - run: terraform apply -auto-approve
